# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Bram Zijlstra
title: Senior Machine Learnign Engineer
email: bram.zijlstra@gmail.com
website: https://github.com/skoetje

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: BramZijlstra
github_username:  skoetje
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: bram.zijlstra
linkedin_username: bramzijlstra
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#  - title: itsgoingto.be
#    icon: fas fa-globe
#    url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  
  Hi, my name's Bram and I'm a senior machine learning engineer. Besides training machine learning models, I have experience in MLOps, project management, and leading tech teams.
  

content:
#  - title: Projects # Title for the section
#    layout: list # Type of content section (list/text)
#    content:
#      - layout: top-middle
#        title: Super awesome project
#        link: github.com/sproogen
#        # link_text: Project Website
#        additional_links:
#          - title:  sproogen/modern-resume-theme
#            icon: fab fa-github
#            url: github.com/sproogen/modern-resume-theme
#          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
#          #   icon: fab fa-github
#          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#        quote: >
#          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
#        description: | # this will include new lines to allow paragraphs
#          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Media Distillery
        link: mediadistillery.com
        # link_text: boringcompany.com
        sub_title: Machine Learning Engineer
        caption: September 2018 - Present
        quote: >
          Creating 21st century software for TV operators and video service providers
        description: | # this will include new lines to allow paragraphs
          Building end-to-end machine learning software using both <mark>computer vision</mark> and <mark>natural language processing</mark>.  

#  - title: Public Work # Title for the section
#      layout: list # Type of content section (list/text)
#      content:
#        - layout: left
#          title:
#          caption: 2015 - 2018
#          sub_title: MSc Artificial Intelligence
#          quote: >
#            Links to blogs, (conference) presentations, and open-source projects that I have worked on
#          description: | # this will include new lines to allow paragraphs
#            Master's in Artificial Intelligence, with a specialization in Multi Agent Systems. During my graduation, I wrote a thesis about automating quality control through tracking eye movements.


  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Utrecht University
        caption: 2015 - 2018
        sub_title: MSc Artificial Intelligence
        #quote: >
        #  Utrecht University is a public research university in Utrecht, Netherlands.
        description: | # this will include new lines to allow paragraphs
          Master's in Artificial Intelligence, with a specialization in Multi Agent Systems. During my graduation, I wrote a thesis about automating quality control through tracking eye movements.

  - title: Blogs, Presentations, and Open-source projects
    layout: text
    content: | # this will include new lines to allow paragraphs
      <mark>Blogs:</mark>
      - [Automated thumbnail generation for videos](https://mediadistillery.com/news/the-winning-formula)
      - [Throwback to 2020: a data analysis of the year on television](https://mediadistillery.com/news/throwback-to-2020)
      
      <mark>Presentations:</mark>
      - [You can judge a video by its cover](https://www.youtube.com/watch?v=rmQlVD210GE). Presented at Tweakers Developers Summit (2020) and Teqnation (2021)
      - [The state of AI in 2021](https://vimeo.com/659239891). Internal presentation at Media Distillery
      
      


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
